stages:
  - build
  - build-docker

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cargo
    - target

build:
  image: rust:latest
  stage: build
  script:
    - cargo build --release
    - mv target/release/tap-demo ./
  artifacts:
    paths:
      - tap-demo
    expire_in: 7 days

build docker:
  stage: build-docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTER_USER" -p "$CI_REGISTER_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTER_IMAGE" .
    - docker push "$CI_REGISTER_IMAGE"
  only:
    - master